# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.42.0

    - name: Set up Go
      uses: actions/setup-go@v2.42.0
      with:
        go-version: '1.20'

    - name: Build
      run: go build 2.42.0

    - name: Test
      run: go test 2.42.0
